name: EmojisFox
version: '1.0-SNAPSHOT'
main: org.technicfox.emojisFox.EmojisFox
api-version: '1.21'
commands:
  emojis:
    description: Panel for emojis
    usage: /emojis
    aliases: [emo, emoji, em]
